name: Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -q

      - name: Run Tests
        run: mvn test

      - name: Sonar
        run: mvn sonar:sonar

      - name: Build Docker Image
        run: |
          docker build -t tractor-app:${{ github.sha }} .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker scout cves tractor-app:${{ github.sha }} .

      - name: Run Docker Image
        run: docker run -d -p 8080:8080 tractor-app:${{ github.sha }}

      # Uncomment when you have Docker Hub credentials set up:
      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag tractor-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/tractor-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tractor-app:latest
